### ISSUE TITLE
What's the problem?

### ISSUE THREAD

**Issue by Pranay1004** [UndeadSec/HeraKeylogger#1]
Traceback (most recent call last):
  File "hera.py", line 21, in <module>
    from core.view import *
  File "/root/HiddenEye/HeraKeylogger/core/view.py", line 13, in <module>
    from huepy import *
ModuleNotFoundError: No module named 'huepy'

**Comment by ErfanPY** [comment]
you just need to install huepy with this code :
pip install huepy==0.9.8.1
